name: CI/CD Books Scraper Docker

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Iniciar sesión en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Construir imagen de Docker
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/books_scraper:latest .

    - name: Ejecutar el scraper en el contenedor
      run: |
        docker run --rm \
          -v "${{ github.workspace }}/src/books_scraper/static/csv":/app/src/books_scraper/static/csv \
          -v "${{ github.workspace }}/src/books_scraper/static/db":/app/src/books_scraper/static/db \
          ${{ secrets.DOCKER_HUB_USERNAME }}/books_scraper:latest

    - name: Subir datos extraídos como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: scraped-data
        path: |
          src/books_scraper/static/csv/books.csv
          src/books_scraper/static/db/books.db

    - name: Confirmar resultados
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add src/books_scraper/static/csv/books.csv src/books_scraper/static/db/books.db
        git commit -m "🤖 Actualización automática de datos [skip ci]" || echo
        "🚫 No hay cambios que commitear"
        git push origin master "No hay cambios que commitear"
        git push origin master